player_manager.AddValidModel("FDF Jaeger 1","models/player/mw3rangers/us_ranger_01.mdl")
player_manager.AddValidHands("FDF Jaeger 1", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
list.Set("PlayerOptionsModel","FDF Jaeger 1","models/player/mw3rangers/us_ranger_01.mdl")
player_manager.AddValidModel("FDF Jaeger 2","models/player/mw3rangers/us_ranger_02.mdl")
player_manager.AddValidHands("FDF Jaeger 2", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
list.Set("PlayerOptionsModel","FDF Jaeger 2","models/player/mw3rangers/us_ranger_02.mdl")
player_manager.AddValidModel("FDF Zombie Jaeger","models/player/mw3rangers/zom_ranger_01.mdl")
player_manager.AddValidHands("FDF Zombie Jaeger", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
list.Set("PlayerOptionsModel","FDF Zombie Jaeger","models/player/mw3rangers/zom_ranger_01.mdl")
player_manager.AddValidModel("FDF Jaeger 3", "models/player/us_00004.mdl" )
player_manager.AddValidHands("FDF Jaeger 3", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
list.Set("PlayerOptionsModel","FDF Jaeger 3", "models/player/us_00004.mdl")